# Generated by Django 6.0 on 2026-02-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_type', models.CharField(choices=[('RCT', 'Rhino Circular Tank'), ('SST', 'Secure Store Micro-Coated Tank'), ('FM', 'FM Tank')], max_length=10)),
                ('model', models.CharField(max_length=20)),
                ('diameter', models.FloatField(help_text='Diameter in meters')),
            ],
            options={
                'unique_together': {('tank_type', 'model')},
            },
        ),
        migrations.CreateModel(
            name='TankCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(help_text='Height in meters')),
                ('capacity', models.FloatField(help_text='Capacity (Liters or m3)')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='calculator.tank')),
            ],
            options={
                'ordering': ['tank', 'height'],
                'unique_together': {('tank', 'height')},
            },
        ),
    ]
