# Generated by Django 6.0.1 on 2026-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(db_index=True, help_text='Full model name with height (e.g., RCT15-22, SST40-36(ETP))', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('RCT', 'Rhino Commercial Tank'), ('SST', 'SecureStore Micro-Coated Tanks'), ('SFM', 'Factory Mutual Tank'), ('GFS', 'Glass Fiber Sheets Tank')], db_index=True, help_text='Tank category: RCT, SST, SFM, GFS', max_length=10)),
                ('diameter', models.FloatField(help_text='Tank diameter in meters')),
                ('height', models.FloatField(help_text='Tank height in meters')),
                ('net_capacity', models.FloatField(help_text='Net capacity in KL (Kiloliters)')),
                ('gross_capacity', models.FloatField(help_text='Gross capacity in KL (Kiloliters)')),
                ('ideal_price', models.DecimalField(decimal_places=2, help_text='Ideal selling price in ₹', max_digits=12)),
                ('nrp', models.DecimalField(decimal_places=2, help_text='No Regret Price in ₹', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tank',
                'verbose_name_plural': 'Tanks',
                'ordering': ['category', 'model'],
                'indexes': [models.Index(fields=['category', 'net_capacity'], name='calculator__categor_960cfd_idx'), models.Index(fields=['category', 'ideal_price'], name='calculator__categor_8f2b45_idx'), models.Index(fields=['diameter', 'height'], name='calculator__diamete_025944_idx')],
            },
        ),
    ]
