# Generated by Django 6.0 on 2026-02-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['tank_type', 'model']},
        ),
        migrations.AlterField(
            model_name='tank',
            name='tank_type',
            field=models.CharField(choices=[('RCT', 'Rhino Circular Tank'), ('SST', 'SecureStore Steel Bolted Storage'), ('FM', 'Field Mounted Tank')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tankcapacity',
            name='capacity',
            field=models.FloatField(help_text='Capacity in source unit (Liters for RCT/FM, m³ for SST)'),
        ),
    ]
