# Generated by Django 6.0.1 on 2026-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active tanks appear in public search. Inactive tanks are hidden.'),
        ),
    ]
