# Generated by Django 5.0.1 on 2026-03-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_tank_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='category',
            field=models.CharField(choices=[('RCT', 'Rhino Commercial Tank'), ('SST', 'SecureStore Micro-Coated Tanks'), ('SFM', 'Factory Mutual Tank'), ('GFS', 'Glass Fused Tank')], db_index=True, help_text='Tank category: RCT, SST, SFM, GFS', max_length=10),
        ),
        migrations.CreateModel(
            name='NexusExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('sales_person', models.CharField(db_index=True, max_length=255)),
                ('tank_count', models.IntegerField(default=0)),
                ('payload', models.JSONField()),
                ('export_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_modified', models.BooleanField(db_index=True, default=False, help_text='True if collection modified in Nexus')),
                ('modification_type', models.CharField(blank=True, help_text="e.g., 'accessories_added', 'tanks_edited'", max_length=50, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nexus_export_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sales_person', 'client_name'], name='nexus_expor_sales_p_27b677_idx'), models.Index(fields=['sales_person', 'is_modified'], name='nexus_expor_sales_p_a8351c_idx')],
            },
        ),
    ]
