# Generated by Django 6.0 on 2026-02-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_tank_options_alter_tank_tank_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='tank_type',
            field=models.CharField(choices=[('RCT', 'Rhino Commercial Tank'), ('SST', 'SecureStore Micro-Coated Tanks'), ('FM', 'Factory Mutual Tank')], max_length=10),
        ),
    ]
